name: Build Android App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v3.3.2  # Or latest version

      - name: Use Gradle Cache (Optional)
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('build.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

    #  - name: Set Up Gradle (Optional)  # You can keep this or remove it
     #   uses: gradle/wrapper-validation@v1  # This can be removed for Gradle 8.x

    #  - name: Install Android SDK (Optional)
        # Uncomment if you need to install SDK within the workflow
       # run: |
         # echo "y" | sdkmanager "platforms;android-34" "build-tools;34.0.4"

      - name: Grant Gradle Permissions
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug -Pandroid.enableJetifier=true  # Optional for R8/ProGuard compatibility
